export const COMPONENTS = [
  // CPUs
  {
    id: "cpu-1",
    name: "Intel Core i9-14900K",
    brand: "Intel",
    category: "cpu",
    price: 52999,
    rating: 4.8,
    reviews: 245,
    specs: {
      socket: "LGA1700",
      cores: 24,
      threads: 32,
      speed: "3.2 GHz (6.0 GHz Turbo)",
      tdp: 125,
    },
  },
  {
    id: "cpu-2",
    name: "AMD Ryzen 7 7800X3D",
    brand: "AMD",
    category: "cpu",
    price: 34999,
    rating: 4.9,
    reviews: 589,
    specs: {
      socket: "AM5",
      cores: 8,
      threads: 16,
      speed: "4.2 GHz (5.0 GHz Turbo)",
      tdp: 120,
    },
  },
  {
    id: "cpu-3",
    name: "AMD Ryzen 9 7950X",
    brand: "AMD",
    category: "cpu",
    price: 52499,
    rating: 4.7,
    reviews: 182,
    specs: {
      socket: "AM5",
      cores: 16,
      threads: 32,
      speed: "4.5 GHz (5.7 GHz Turbo)",
      tdp: 170,
    },
  },
  {
    id: "cpu-4",
    name: "Intel Core i7-14700K",
    brand: "Intel",
    category: "cpu",
    price: 38999,
    rating: 4.6,
    reviews: 198,
    specs: {
      socket: "LGA1700",
      cores: 20,
      threads: 28,
      speed: "3.4 GHz (5.6 GHz Turbo)",
      tdp: 125,
    },
  },
  {
    id: "cpu-5",
    name: "AMD Ryzen 5 7600X",
    brand: "AMD",
    category: "cpu",
    price: 19999,
    rating: 4.5,
    reviews: 312,
    specs: {
      socket: "AM5",
      cores: 6,
      threads: 12,
      speed: "4.7 GHz (5.3 GHz Turbo)",
      tdp: 105,
    },
  },

  // GPUs
  {
    id: "gpu-1",
    name: "NVIDIA GeForce RTX 4090",
    brand: "NVIDIA",
    category: "gpu",
    price: 174999,
    rating: 4.9,
    reviews: 412,
    specs: {
      vram: "24GB GDDR6X",
      length: 336,
      wattage: 450,
      interface: "PCIe 4.0 x16",
    },
  },
  {
    id: "gpu-2",
    name: "NVIDIA GeForce RTX 4080 Super",
    brand: "NVIDIA",
    category: "gpu",
    price: 104999,
    rating: 4.8,
    reviews: 218,
    specs: {
      vram: "16GB GDDR6X",
      length: 310,
      wattage: 320,
      interface: "PCIe 4.0 x16",
    },
  },
  {
    id: "gpu-3",
    name: "AMD Radeon RX 7900 XTX",
    brand: "AMD",
    category: "gpu",
    price: 95999,
    rating: 4.7,
    reviews: 167,
    specs: {
      vram: "24GB GDDR6",
      length: 287,
      wattage: 355,
      interface: "PCIe 4.0 x16",
    },
  },
  {
    id: "gpu-4",
    name: "NVIDIA GeForce RTX 4070 Ti Super",
    brand: "NVIDIA",
    category: "gpu",
    price: 82999,
    rating: 4.6,
    reviews: 145,
    specs: {
      vram: "16GB GDDR6X",
      length: 285,
      wattage: 285,
      interface: "PCIe 4.0 x16",
    },
  },
  {
    id: "gpu-5",
    name: "AMD Radeon RX 7800 XT",
    brand: "AMD",
    category: "gpu",
    price: 51999,
    rating: 4.6,
    reviews: 289,
    specs: {
      vram: "16GB GDDR6",
      length: 267,
      wattage: 263,
      interface: "PCIe 4.0 x16",
    },
  },

  // Motherboards
  {
    id: "mobo-1",
    name: "ASUS ROG Maximus Z790 Hero",
    brand: "ASUS",
    category: "motherboard",
    price: 59999,
    rating: 4.7,
    reviews: 98,
    specs: {
      socket: "LGA1700",
      formFactor: "ATX",
      memoryType: "DDR5",
      maxMemory: "192GB",
    },
  },
  {
    id: "mobo-2",
    name: "MSI MAG B650 Tomahawk WiFi",
    brand: "MSI",
    category: "motherboard",
    price: 21999,
    rating: 4.8,
    reviews: 432,
    specs: {
      socket: "AM5",
      formFactor: "ATX",
      memoryType: "DDR5",
      maxMemory: "192GB",
    },
  },
  {
    id: "mobo-3",
    name: "GIGABYTE X670E AORUS Master",
    brand: "GIGABYTE",
    category: "motherboard",
    price: 42999,
    rating: 4.6,
    reviews: 74,
    specs: {
      socket: "AM5",
      formFactor: "ATX",
      memoryType: "DDR5",
      maxMemory: "192GB",
    },
  },
  {
    id: "mobo-4",
    name: "ASUS Prime Z790-A WiFi",
    brand: "ASUS",
    category: "motherboard",
    price: 26999,
    rating: 4.4,
    reviews: 121,
    specs: {
      socket: "LGA1700",
      formFactor: "ATX",
      memoryType: "DDR5",
      maxMemory: "192GB",
    },
  },
  {
    id: "mobo-5",
    name: "ASRock B650M Pro RS",
    brand: "ASRock",
    category: "motherboard",
    price: 14999,
    rating: 4.5,
    reviews: 198,
    specs: {
      socket: "AM5",
      formFactor: "Micro ATX",
      memoryType: "DDR5",
      maxMemory: "192GB",
    },
  },

  // RAM
  {
    id: "ram-1",
    name: "G.Skill Trident Z5 RGB 32GB (2x16GB) DDR5-6000",
    brand: "G.Skill",
    category: "ram",
    price: 11999,
    rating: 4.8,
    reviews: 512,
    specs: {
      type: "DDR5",
      speed: "6000 MHz",
      capacity: "32GB",
      latency: "CL30",
    },
  },
  {
    id: "ram-2",
    name: "Corsair Vengeance RGB 32GB (2x16GB) DDR5-6000",
    brand: "Corsair",
    category: "ram",
    price: 11499,
    rating: 4.7,
    reviews: 382,
    specs: {
      type: "DDR5",
      speed: "6000 MHz",
      capacity: "32GB",
      latency: "CL36",
    },
  },
  {
    id: "ram-3",
    name: "Corsair Vengeance LPX 16GB (2x8GB) DDR4-3200",
    brand: "Corsair",
    category: "ram",
    price: 4499,
    rating: 4.8,
    reviews: 1240,
    specs: {
      type: "DDR4",
      speed: "3200 MHz",
      capacity: "16GB",
      latency: "CL16",
    },
  },
  {
    id: "ram-4",
    name: "G.Skill Ripjaws V 32GB (2x16GB) DDR4-3200",
    brand: "G.Skill",
    category: "ram",
    price: 6999,
    rating: 4.7,
    reviews: 843,
    specs: {
      type: "DDR4",
      speed: "3200 MHz",
      capacity: "32GB",
      latency: "CL16",
    },
  },

  // Storage
  {
    id: "storage-1",
    name: "Samsung 990 Pro 2TB M.2 PCIe 4.0 NVMe",
    brand: "Samsung",
    category: "storage",
    price: 16999,
    rating: 4.9,
    reviews: 853,
    specs: {
      type: "NVMe SSD",
      capacity: "2TB",
      readSpeed: "7450 MB/s",
    },
  },
  {
    id: "storage-2",
    name: "Crucial T700 2TB PCIe 5.0 NVMe",
    brand: "Crucial",
    category: "storage",
    price: 24999,
    rating: 4.6,
    reviews: 112,
    specs: {
      type: "NVMe SSD",
      capacity: "2TB",
      readSpeed: "12400 MB/s",
    },
  },
  {
    id: "storage-3",
    name: "WD Black SN850X 2TB M.2 NVMe",
    brand: "Western Digital",
    category: "storage",
    price: 14999,
    rating: 4.8,
    reviews: 472,
    specs: {
      type: "NVMe SSD",
      capacity: "2TB",
      readSpeed: "7300 MB/s",
    },
  },
  {
    id: "storage-4",
    name: "Crucial MX500 1TB 2.5\" SATA SSD",
    brand: "Crucial",
    category: "storage",
    price: 7999,
    rating: 4.7,
    reviews: 2198,
    specs: {
      type: "SATA SSD",
      capacity: "1TB",
      readSpeed: "560 MB/s",
    },
  },

  // PSUs
  {
    id: "psu-1",
    name: "Corsair RM1000x 1000W 80+ Gold",
    brand: "Corsair",
    category: "psu",
    price: 18999,
    rating: 4.9,
    reviews: 582,
    specs: {
      wattage: 1000,
      efficiency: "80+ Gold",
      modularity: "Full",
    },
  },
  {
    id: "psu-2",
    name: "Seasonic Focus GX-850 850W 80+ Gold",
    brand: "Seasonic",
    category: "psu",
    price: 11999,
    rating: 4.8,
    reviews: 312,
    specs: {
      wattage: 850,
      efficiency: "80+ Gold",
      modularity: "Full",
    },
  },
  {
    id: "psu-3",
    name: "EVGA SuperNOVA 750 GT 750W 80+ Gold",
    brand: "EVGA",
    category: "psu",
    price: 9999,
    rating: 4.6,
    reviews: 245,
    specs: {
      wattage: 750,
      efficiency: "80+ Gold",
      modularity: "Full",
    },
  },
  {
    id: "psu-4",
    name: "be quiet! Dark Power 13 1300W 80+ Titanium",
    brand: "be quiet!",
    category: "psu",
    price: 28999,
    rating: 4.8,
    reviews: 43,
    specs: {
      wattage: 1300,
      efficiency: "80+ Titanium",
      modularity: "Full",
    },
  },

  // Cases
  {
    id: "case-1",
    name: "Lian Li O11 Dynamic EVO",
    brand: "Lian Li",
    category: "case",
    price: 14999,
    rating: 4.9,
    reviews: 672,
    specs: {
      type: "Mid Tower",
      gpuMaxLength: 426,
      sidePanel: "Tempered Glass",
    },
  },
  {
    id: "case-2",
    name: "NZXT H9 Flow",
    brand: "NZXT",
    category: "case",
    price: 15999,
    rating: 4.8,
    reviews: 489,
    specs: {
      type: "Mid Tower",
      gpuMaxLength: 435,
      sidePanel: "Tempered Glass",
    },
  },
  {
    id: "case-3",
    name: "Fractal Design North (Walnut)",
    brand: "Fractal Design",
    category: "case",
    price: 13999,
    rating: 4.9,
    reviews: 312,
    specs: {
      type: "Mid Tower",
      gpuMaxLength: 355,
      sidePanel: "Mesh & Wood",
    },
  },
  {
    id: "case-4",
    name: "Corsair 4000D Airflow",
    brand: "Corsair",
    category: "case",
    price: 9499,
    rating: 4.7,
    reviews: 1542,
    specs: {
      type: "Mid Tower",
      gpuMaxLength: 360,
      sidePanel: "Tempered Glass",
    },
  },

  // Coolers
  {
    id: "cooler-1",
    name: "NZXT Kraken 360 Elite RGB",
    brand: "NZXT",
    category: "cooler",
    price: 27999,
    rating: 4.8,
    reviews: 198,
    specs: {
      type: "Liquid AIO",
      radiatorSize: "360mm",
      socketsSupported: ["LGA1700", "AM5", "AM4"],
    },
  },
  {
    id: "cooler-2",
    name: "Noctua NH-D15 chromax.black",
    brand: "Noctua",
    category: "cooler",
    price: 11999,
    rating: 4.9,
    reviews: 873,
    specs: {
      type: "Air",
      radiatorSize: "N/A",
      socketsSupported: ["LGA1700", "AM5", "AM4", "LGA1200"],
    },
  },
  {
    id: "cooler-3",
    name: "Thermalright Peerless Assassin 120 SE",
    brand: "Thermalright",
    category: "cooler",
    price: 3599,
    rating: 4.8,
    reviews: 2194,
    specs: {
      type: "Air",
      radiatorSize: "N/A",
      socketsSupported: ["LGA1700", "AM5", "AM4"],
    },
  },
  {
    id: "cooler-4",
    name: "Corsair iCUE Link H150i RGB",
    brand: "Corsair",
    category: "cooler",
    price: 23999,
    rating: 4.7,
    reviews: 134,
    specs: {
      type: "Liquid AIO",
      radiatorSize: "360mm",
      socketsSupported: ["LGA1700", "AM5", "AM4"],
    },
  },
];

export const COMMUNITY_BUILDS = [
  {
    id: "build-1",
    name: "Nebula Overlord Edition",
    author: "AlphaBuilder99",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=100&q=80",
    description: "Ultimate workstation and gaming rig designed for 4K streaming and high-fidelity ray-tracing.",
    cpu: "Intel Core i9-14900K",
    gpu: "NVIDIA GeForce RTX 4090",
    mobo: "ASUS ROG Maximus Z790 Hero",
    ram: "G.Skill Trident Z5 RGB 32GB DDR5-6000",
    storage: "Samsung 990 Pro 2TB",
    psu: "Corsair RM1000x 1000W",
    casePart: "Lian Li O11 Dynamic EVO",
    cooler: "NZXT Kraken 360 Elite RGB",
    totalPrice: 359999,
    upvotes: 432,
    comments: 48,
    category: "enthusiast",
    date: "2026-05-24",
  },
  {
    id: "build-2",
    name: "Frostbite Gaming Concept",
    author: "SnowDrift",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100&q=80",
    description: "A clean, white themed build running the gaming king Ryzen 7 7800X3D with a powerful RTX 4080 Super.",
    cpu: "AMD Ryzen 7 7800X3D",
    gpu: "NVIDIA GeForce RTX 4080 Super",
    mobo: "MSI MAG B650 Tomahawk WiFi",
    ram: "Corsair Vengeance RGB 32GB DDR5-6000",
    storage: "WD Black SN850X 2TB",
    psu: "Seasonic Focus GX-850 850W",
    casePart: "NZXT H9 Flow",
    cooler: "Corsair iCUE Link H150i RGB",
    totalPrice: 219999,
    upvotes: 312,
    comments: 29,
    category: "gaming",
    date: "2026-05-28",
  },
  {
    id: "build-3",
    name: "Minimalist Walnut Workspace",
    author: "DesignFirst",
    avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=100&q=80",
    description: "A quiet, professional development setup focusing on CPU compiling performance with a sleek natural wood design.",
    cpu: "AMD Ryzen 9 7950X",
    gpu: "AMD Radeon RX 7800 XT",
    mobo: "GIGABYTE X670E AORUS Master",
    ram: "G.Skill Trident Z5 RGB 32GB DDR5-6000",
    storage: "Crucial T700 2TB",
    psu: "Corsair RM1000x 1000W",
    casePart: "Fractal Design North (Walnut)",
    cooler: "Noctua NH-D15 chromax.black",
    totalPrice: 199999,
    upvotes: 215,
    comments: 18,
    category: "workstation",
    date: "2026-05-30",
  },
  {
    id: "build-4",
    name: "Stealth Budget Fighter",
    author: "NoRGBGuy",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&q=80",
    description: "Zero RGB components, high value, incredible performance per dollar focused strictly on 1440p gaming.",
    cpu: "AMD Ryzen 5 7600X",
    gpu: "AMD Radeon RX 7800 XT",
    mobo: "ASRock B650M Pro RS",
    ram: "G.Skill Ripjaws V 32GB DDR4-3200",
    storage: "Crucial MX500 1TB",
    psu: "EVGA SuperNOVA 750 GT 750W",
    casePart: "Corsair 4000D Airflow",
    cooler: "Thermalright Peerless Assassin 120 SE",
    totalPrice: 99999,
    upvotes: 184,
    comments: 24,
    category: "budget",
    date: "2026-05-15",
  },
];

export const PREBUILT_PCS = [
  {
    id: "pc-1",
    name: "Aetheris Genesis X",
    brand: "IC PC's Elite",
    category: "gaming",
    price: 369999,
    rating: 4.9,
    reviews: 84,
    image: "/images/gaming_pc.png",
    description: "Ultimate luxury liquid-cooled battle station designed for max 4K ray-traced gaming, virtual reality, and intensive rendering workloads.",
    specs: {
      cpu: "Intel Core i9-14900K (24-Core)",
      gpu: "NVIDIA GeForce RTX 4090 24GB",
      ram: "64GB DDR5 G.Skill Trident Z5 6000MHz",
      storage: "4TB Samsung 990 Pro NVMe Gen4 SSD",
      motherboard: "ASUS ROG Maximus Z790 Hero",
      psu: "Corsair RM1000x 1000W 80+ Gold",
      cooler: "NZXT Kraken 360 Elite RGB AIO",
      case: "Lian Li O11 Dynamic EVO (Glass)"
    }
  },
  {
    id: "pc-2",
    name: "Chronos Creator Studio",
    brand: "IC PC's Pro",
    category: "workstation",
    price: 429999,
    rating: 4.8,
    reviews: 29,
    image: "/images/workstation_pc.png",
    description: "Professional grade creator workhorse featuring natural walnut wood paneling, massive memory bandwidth, and whisper-quiet cooling.",
    specs: {
      cpu: "AMD Ryzen 9 7950X (16-Core)",
      gpu: "NVIDIA GeForce RTX 4090 24GB",
      ram: "128GB DDR5 Corsair Vengeance 5600MHz",
      storage: "8TB Dual Crucial T700 PCIe 5.0 SSD",
      motherboard: "GIGABYTE X670E AORUS Master",
      psu: "be quiet! Dark Power 13 1300W Titanium",
      cooler: "Noctua NH-D15 Chromax Black Air",
      case: "Fractal Design North Walnut (Mesh & Wood)"
    }
  },
  {
    id: "pc-3",
    name: "Wraith Stealth Edition",
    brand: "IC PC's Value",
    category: "budget",
    price: 129999,
    rating: 4.7,
    reviews: 142,
    image: "/images/gaming_pc.png",
    description: "High performance per dollar gaming PC featuring zero-RGB stealth styling, optimized for ultra 1440p gaming experiences.",
    specs: {
      cpu: "AMD Ryzen 5 7600X (6-Core)",
      gpu: "AMD Radeon RX 7800 XT 16GB",
      ram: "32GB DDR5 G.Skill Ripjaws V 6000MHz",
      storage: "2TB WD Black SN850X NVMe SSD",
      motherboard: "ASRock B650M Pro RS WiFi",
      psu: "Seasonic Focus GX-850 850W Gold",
      cooler: "Thermalright Peerless Assassin 120 SE",
      case: "Corsair 4000D Airflow Black"
    }
  }
];

export const LAPTOPS = [
  {
    id: "lap-1",
    name: "ROG Zephyrus G16 Cyber",
    brand: "ASUS ROG",
    category: "enthusiast",
    price: 279999,
    rating: 4.8,
    reviews: 73,
    image: "/images/gaming_laptop.png",
    description: "Ultra-thin, premium metal gaming laptop featuring a gorgeous 240Hz OLED display, custom vapor chamber cooling, and intelligent power delivery.",
    specs: {
      cpu: "Intel Core Ultra 9 185H",
      gpu: "NVIDIA GeForce RTX 4090 Laptop 16GB",
      ram: "32GB LPDDR5X 7467MHz",
      storage: "2TB PCIe 4.0 NVMe M.2 SSD",
      display: "16-inch 2.5K QHD+ 240Hz ROG Nebula OLED",
      battery: "90Wh with 240W Fast Charge",
      weight: "1.85 kg"
    }
  },
  {
    id: "lap-2",
    name: "Alienware m18 Aurora",
    brand: "Alienware",
    category: "gaming",
    price: 249999,
    rating: 4.7,
    reviews: 49,
    image: "/images/gaming_laptop.png",
    description: "Desktop replacement gaming laptop packing massive cooling power, Element 31 thermal interface, and mechanical cherry MX keys.",
    specs: {
      cpu: "Intel Core i9-14900HX",
      gpu: "NVIDIA GeForce RTX 4080 Laptop 12GB",
      ram: "32GB DDR5 5600MHz Dual-Channel",
      storage: "2TB PCIe 4.0 NVMe M.2 SSD",
      display: "18-inch QHD+ 16:10 480Hz ComfortView Plus",
      battery: "97Wh with 330W GaN Adapter",
      weight: "4.23 kg"
    }
  },
  {
    id: "lap-3",
    name: "Razer Blade 16 Luxury",
    brand: "Razer",
    category: "enthusiast",
    price: 389999,
    rating: 4.9,
    reviews: 32,
    image: "/images/gaming_laptop.png",
    description: "CNC aluminum anodized chassis with dual-mode Mini-LED display capability (switch between 4K 120Hz and FHD+ 240Hz on the fly).",
    specs: {
      cpu: "Intel Core i9-14900HX",
      gpu: "NVIDIA GeForce RTX 4090 Laptop 16GB",
      ram: "64GB DDR5 5600MHz (Upgradable)",
      storage: "4TB (Dual 2TB NVMe PCIe 4.0 SSD)",
      display: "16-inch Dual-Mode Mini-LED (UHD+ 120Hz / FHD+ 240Hz)",
      battery: "95.2Wh with 330W GaN Charger",
      weight: "2.45 kg"
    }
  },
  {
    id: "lap-4",
    name: "MSI Raider GE78 RGB",
    brand: "MSI",
    category: "gaming",
    price: 179999,
    rating: 4.6,
    reviews: 114,
    image: "/images/gaming_laptop.png",
    description: "Performance beast with light-bar front diffuser, cooler boost 5 tech, and Dynaudio surround system.",
    specs: {
      cpu: "Intel Core i7-14700HX",
      gpu: "NVIDIA GeForce RTX 4070 Laptop 8GB",
      ram: "32GB DDR5 5600MHz",
      storage: "1TB PCIe 4.0 NVMe SSD",
      display: "17-inch QHD+ 240Hz IPS-Level 100% DCI-P3",
      battery: "99.9Wh (Maximum legal flight limit)",
      weight: "3.10 kg"
    }
  }
];
